### your site title here

title: Giavanna Jadick
description: PhD Student | University of Chicago | Medical Physics

baseurl: "/" #name of GitHub repository
url: "https://gjadick.github.com" #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "giajadick"
linkedin: "giajadick"
github: "gjadick"
orcid: "0000-0002-4894-2895"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - 110_MVkV.md
      - 120_Outreach.md
      - 200_FBPrecon.md
      - 810_DukeSim.md
      - 910_SaxAcoustics.md
      - 920_Biophysics.md


sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
